MODEL:
  META_ARCHITECTURE: "CenterNet"
  MASK_ON: False
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  CENTERNET:
    DECONV_CHANNEL: [512, 256, 128, 64]
    DECONV_KERNEL: [4, 4, 4]
    NUM_CLASSES: 1
    MODULATE_DEFORM: True
    BIAS_VALUE: -2.19
    DOWN_SCALE: 4
    MIN_OVERLAP: 0.7
    TENSOR_DIM: 128
DATASETS:
  TRAIN: ("balloon_train",)
  TEST: ("balloon_val",)
SOLVER:
  IMS_PER_BATCH: 2
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.0001
  STEPS: (30000, 40000)
  MAX_ITER: 45000
TEST:
  EVAL_PERIOD: 300
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
