MODEL:
  META_ARCHITECTURE: "YOLOF"
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    OUT_FEATURES: ["res5"]
DATASETS:
  TRAIN: ("hci_train",)
  TEST: ("hci_val",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00005
  WARMUP_FACTOR: 0.00066667
  WARMUP_ITERS: 1500
  STEPS: (15000, 20000)
  MAX_ITER: 22500
  CHECKPOINT_PERIOD: 2500
INPUT:
  MIN_SIZE_TRAIN: (800,)