_BASE_: "Base-YOLOF.yaml"
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/FAIR/X-101-64x4d"
  RESNETS:
    DEPTH: 101
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
    STRIDE_IN_1X1: False
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.06
  WARMUP_FACTOR: 0.000334
  WARMUP_ITERS: 3000
  STEPS: (30000, 40000)
  MAX_ITER: 45000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "output/yolof/X_101_64x4d_C5_1x"
