_BASE_: "yolof_R_101_C5_1x.yaml"
MODEL:
  RESNETS:
    RES5_DILATION: 2
  ANCHOR_GENERATOR:
    SIZES: [[16, 32, 64, 128, 256, 512]]
  YOLOF:
    ENCODER:
      BLOCK_DILATIONS: [4, 8, 12, 16]
    DECODER:
      NUM_ANCHORS: 6
    MATCHER:
      TOPK: 8
    POS_IGNORE_THRESHOLD: 0.1
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.06
  WARMUP_FACTOR: 0.000334
  WARMUP_ITERS: 3000
  STEPS: (30000, 40000)
  MAX_ITER: 45000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "output/yolof/R_101_DC5_1x"
