_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "/home/changliu/PycharmProjects/paths/r50_100pro_3x_model.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("balloon_train",)
  TEST:  ("balloon_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
